version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: BackendDockerfile
    ports:
      - "443:8080"
    volumes:
      - ./data:/app/data  # Map the ./data directory on the host to /app/data in the container
    environment:
      - GRAPH_URL_HOST=http://3.143.235.233:8080
      - DATA_FLD=data_mac
    entrypoint: /bin/bash -c "uvicorn main:app --host 0.0.0.0 --port 8080"
  frontend:
    build:
      context: ./chat-langchain
      dockerfile: FrontendDockerfile
    ports:
      - "80:3000"
    entrypoint: ["yarn", "dev"]
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://3.131.185.39:443
